# Generated by Django 5.0 on 2024-01-01 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0002_category_alter_produit_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='my_blog.category'),
            preserve_default=False,
        ),
    ]
